---
title: "Swiss Rainfall"
author: "Kebarileng Molefe"
date: "2023-11-17"
output: html_document
---

```{r}
library(geoR)
points(sic.100, borders=sic.borders,col="green")
points(sic.367, borders=sic.borders,col="red",add=TRUE)
```

```{r}

library("geoR")
vario.ex<- variog(sic.100, bin.cloud=TRUE)
plot(vario.ex,main="")
lines.variomodel(cov.model="spher",cov.pars=c(15000,50),
nug=0,max.dist=300)
```

```{r}
library("geoR")
pred.grid <- expand.grid(seq(0,350, l=51),seq (0,220, l=51))
rgb.palette <- colorRampPalette(c("blue", "lightblue",
"orange", "red"),space = "rgb")
kc<- krige.conv(sic.100, loc = pred.grid,
krige=krige.control(cov.model="spherical",cov.pars=c(15000,50)))
image(kc, loc = pred.grid,col =rgb.palette(20) ,xlab="Coord X",
ylab="Coord Y",borders=sic.borders,main="Estimation")
krige.var <- kc$krige.var 
image(kc,krige.var,loc = pred.grid,col = rgb.palette(20),xlab = "Coord X", ylab = "Coord Y", borders = sic.borders, main = "Kriging Variance")

```

```{r}
library("geoR")
kc1<- krige.conv(sic.100, loc = sic.100$coords,
krige=krige.control(cov.model="spherical",cov.pars=c(16000,47)))
kc2<- krige.conv(sic.100, loc = sic.367$coords,
krige=krige.control(cov.model="spherical",cov.pars=c(16000,47)))
plot(sic.100$data,kc1$predict,xlab="Observed",ylab="Estimated",
main="Control sample")
abline(a=0,b=1,col="red")
plot(sic.367$data,kc2$predict,,xlab="Observed",ylab="Estimated",
main="Control")
abline(a=0,b=1,col="red")
```

```{r}
library("geoR")
plot.geodata(sic.100,bor=sic.borders,lambda=0.5)

```

```{r}

library("geoR")
vario.ext <- variog(sic.100, option = "bin", lambda = 0.5)
plot(vario.ext)
lines.variomodel(cov.m = "mat", cov.p = c(105, 36), nug = 6.9,
                 max.dist = 300, kappa = 1, lty = 1)
```

```{r}

library(geoR)
kct<- krige.conv(sic.100, loc = pred.grid,
krige=krige.control(cov.model="matern",cov.pars=c(105, 36),
kappa=1,nugget=6.9,lambda=0.5))
pred.grid <- expand.grid(seq(0,350, l=51),seq (0,220, l=51))
rgb.palette <- colorRampPalette(c("blue", "lightblue",
"orange", "red"),space = "rgb")
image(kct, loc = pred.grid,col =rgb.palette(20) , xlab="Coord X",
ylab="Coord Y",borders=sic.borders,main="Estimation")
image(kct, krige.var,loc = pred.grid,col =rgb.palette(20) ,
xlab="Coord X",ylab="Coord Y",borders=sic.borders,
main="Kriging variance")
```

```{r}
library(geoR)
kct1<- krige.conv(sic.100, loc = sic.100$coords,
krige=krige.control(cov.model="spherical",cov.pars=c(16000,47),
kappa=1,nugget=6.9,lambda=0.5))
kct2<- krige.conv(sic.100, loc = sic.367$coords,
krige=krige.control(cov.model="spherical",cov.pars=c(16000,47),
kappa=1,nugget=6.9,lambda=0.5))
plot(sic.100$data,kct1$predict,xlab="Observed",ylab="Estimated",
main="Sample")
abline(a=0,b=1,col="red")
plot(sic.367$data,kct2$predict,,xlab="Observed",ylab="Estimated",
main="Control sample")
abline(a=0,b=1,col="red")

```